'use server';
/**
 * @fileOverview This file defines a Genkit flow that takes user input, detects the intent, extracts entities,
 * and generates a response using the Gemini Pro API.
 *
 * - generateResponseFromIntentAndEntities - A function that orchestrates intent detection, entity extraction, and response generation.
 * - GenerateResponseInput - The input type for the generateResponseFromIntentAndEntities function.
 * - GenerateResponseOutput - The return type for the generateResponseFromIntentAndEntities function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import type { Task } from '@/lib/types';


const GenerateResponseInputSchema = z.object({
  userInput: z.string().describe('The user input text.'),
  // optional conversation history (oldest -> newest) serialized as text
  history: z.string().optional().describe('Conversation history text, oldest-first'),
});
export type GenerateResponseInput = z.infer<typeof GenerateResponseInputSchema>;

const GenerateResponseOutputSchema = z.object({
  response: z.string().describe('The response generated by the LLM.'),
  intent: z.string().describe('The identified intent of the message.'),
  entities: z.array(z.string()).describe('The identified entities in the message.'),
  task: z.object({
    type: z.enum(['Task', 'Reminder', 'Alarm']),
    content: z.string(),
    time: z.string().optional(),
  }).nullable().describe('The task object if a task was created.'),
  shouldCreateTask: z.boolean().optional(),
  taskType: z.string().optional(),
  taskContent: z.string().optional(),
  taskTime: z.string().optional(),
});
export type GenerateResponseOutput = z.infer<typeof GenerateResponseOutputSchema>;

export async function generateResponseFromIntentAndEntities(
  input: GenerateResponseInput
): Promise<GenerateResponseOutput> {
  return generateResponseFlow(input);
}

const taskSchema = z.object({
    type: z.enum(['Task', 'Reminder', 'Alarm']),
    content: z.string(),
    time: z.string().optional().describe('The time for the task in ISO 8601 format, e.g., 2024-08-15T14:00:00'),
});

const manageTasksTool = ai.defineTool({
    name: 'manageTasks',
    description: 'Use this tool to manage tasks, reminders, and alarms. You can add, remove, or view them.',
    inputSchema: z.object({
        operation: z.enum(['add', 'remove', 'view']),
        task: taskSchema.optional(),
    }),
    outputSchema: taskSchema.nullable(),
}, async ({ operation, task }) => {
    if (operation === 'add' && task) {
        console.log('Adding task via tool:', task);
        // This tool just returns the task object. The caller will handle saving it.
        return task;
    }
    return null;
});


const generateResponsePrompt = ai.definePrompt({
  name: 'generateResponsePrompt',
  input: {schema: GenerateResponseInputSchema},
  output: {schema: z.object({
    intent: z.string(),
    entities: z.array(z.string()),
    response: z.string(),
    shouldCreateTask: z.boolean().optional(),
    taskType: z.string().optional(),
    taskContent: z.string().optional(),
    taskTime: z.string().optional(),
  })},
  prompt: `You are SABA, a personal AI that remembers context across turns and sessions.

CONVERSATION HISTORY (oldest → newest):
{{#if history}}
{{history}}
{{else}}
No prior messages.
{{/if}}

CURRENT MESSAGE:
{{userInput}}

INSTRUCTIONS:
- Read and leverage the conversation history to stay consistent.
- If the user is referring to a previous topic, acknowledge it explicitly (e.g., "Are you referring to our earlier discussion about ...?").
- Be concise and helpful. Create tasks/reminders if clearly requested.

Return ONLY a compact JSON object with keys: intent, entities, response, shouldCreateTask, taskType, taskContent, taskTime.`,
});

const generateResponseFlow = ai.defineFlow(
  {
    name: 'generateResponseFlow',
    inputSchema: GenerateResponseInputSchema,
    outputSchema: GenerateResponseOutputSchema,
  },
  async input => {
    try {
      console.log('Sending to LLM:', JSON.stringify(input, null, 2));
      const result = await generateResponsePrompt(input);
      console.log('Got LLM response:', JSON.stringify(result.output, null, 2));

      // Handle task creation if needed
      let task = null;
      if (result.output?.shouldCreateTask && result.output?.taskContent) {
        task = {
          type: (result.output.taskType as 'Task' | 'Reminder' | 'Alarm') || 'Task',
          content: result.output.taskContent,
          time: result.output.taskTime || undefined,
        };
        console.log('Creating task:', task);
      }

      return {
        response: result.output!.response,
        intent: result.output!.intent,
        entities: result.output!.entities,
        task: task,
        shouldCreateTask: result.output!.shouldCreateTask,
        taskType: result.output!.taskType as 'Task' | 'Reminder' | 'Alarm' | undefined,
        taskContent: result.output!.taskContent,
        taskTime: result.output!.taskTime,
      };
    } catch (err) {
      console.error('Error calling generateResponsePrompt:', err);
      throw err;
    }
  }
);
