name: Deploy Frontend to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Install Vercel CLI
        run: |
          npm install -g vercel@28

      - name: Deploy to Vercel (CLI)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --token $VERCEL_TOKEN --prod --confirm
